#!/bin/bash

DAEMON_PATH=/opt/btce-mobile/util/watchdog/

DAEMON=watchdog-kludged.sh

NAME=btce-watchdog
DESC="BTC-E watchdog for currencies"
PIDFILE=/var/run/$NAME.pid
CHILDPIDFILE=/tmp/$NAME.pid
LOGFILE=/var/log/$NAME.log
SCRIPTNAME=/etc/init.d/$NAME

case "$1" in
start)
        echo "Starting $NAME..."
        cd $DAEMON_PATH
        PID=`bash $DAEMON >> $LOGFILE 2>&1 & echo $!`

        if [ -z $PID ]; then
                printf "%s\n" "Fail"
        else
                echo $PID > $PIDFILE
        fi
;;
stop)
        echo "Stopping $NAME..."
                PID=`cat $PIDFILE`
                cd $DAEMON_PATH
        if [ -f $PIDFILE ]; then
                kill -HUP $PID
                kill -HUP `cat $CHILDPIDFILE`
                printf "%s\n" "Ok"
                rm -f $PIDFILE
        else
                printf "%s\n" "pidfile not found"
        fi
;;
restart)
        $0 stop
        $0 start
;;
*)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
